# File autogenerated at Tue Nov  5 16:21:36 AEDT 2024

module "security-services-ap-southeast-2" {
  source = "/Users/peterhanssens/cloudshuttle/cloudshuttle/org-kickstart/modules/security_services"
  providers = {
    aws.security_account = aws.security-account-ap-southeast-2
    aws.payer_account    = aws.payer-ap-southeast-2
  }
  security_account_id = module.organization.security_account_id
  security_services   = var.organization["security_services"]
  macie_key_arn       = module.organization.macie_key_arn
  macie_bucket_name   = var.organization["macie_bucket_name"]
}
