# File autogenerated at Tue Nov  5 16:21:36 AEDT 2024

provider "aws" {
  alias  = "security-account-ap-southeast-2"
  region = "ap-southeast-2"
  assume_role {
    role_arn = "arn:aws:iam::${module.organization.security_account_id}:role/OrganizationAccountAccessRole"
  }
  default_tags {
    tags = local.default_tags
  }
}
